{{- if and .Values.registrySecret.dockerconfigjson (not .Values.registrySecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhaii.fullname" . }}-registry
  labels:
    {{- include "rhaii.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registrySecret.dockerconfigjson }}
{{- end }}
